version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      - ./images:/app/images
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HOST=0.0.0.0